environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  build-dev:
    group: gocd-example
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/chriscasey/django-rest-swagger
    stages:
      - build-stage: # name of stage
          jobs:
            build-job: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: ./build