environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  build-dev:
    group: gocd-example
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/chriscasey/django-rest-swagger
    stages:
      - build-stage: # name of stage
          jobs:
            build-and-test-job:
              tasks:
                - exec:
                    command: pipenv
                    arguments:
                      - install 
                - exec:    
                    command: pipenv
                    arguments:
                      - run
                      - python
                      - runtests.py  
