environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  gocd-docker-swagger-dev:
    group: dev-group
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/chriscasey/django-rest-swagger
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: echo
                   arguments: - hello